### ISSUE TITLE
Provide mechanism to use a Galaxy callback for data downloads

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/specifications#15]
As per the discussion around iReceptor Gateway and ImmuneML Galaxy, we want to implement the ability for Galaxy to send a Galaxy user to the iReceptor downloads page with a Galaxy callback URL. The Gateway will allow the user to choose a data set from their downloads and then use the Galaxy callback URL to notify Galaxy where the data is so Galaxy can download it...

**Comment by bcorrie** [comment]
Workflow that we are working towards as I understand it:

1. Galaxy sends the user to the iReceptor downloads page: https://gateway.ireceptor.org/downloads&GALAXY_URL=XXX
  - If the user is logged in, this works, and the iReceptor Gateway records the GALAXY_URL for the user.
  - If the user isn’t logged in, the user has to log in, and then is redirected to the downloads page. The iReceptor Gateway records the GALAXY_URL for the user.
  - For each download, there is a menu of what one can do with a download. It always has a “Download” option, but if GALAXY_URL is set, then one also has a “Process with Galaxy” option.
  - If the user chooses “Process with Galaxy” the below would occur.
2. Upon clicking on the button, iReceptor will redirect back to Galaxy (to GALAXY_URL) with 302 code and provide these parameters (with POST):
  - URL: this will be the url where Galaxy can download the data. The documentation says the url must work like this: “The page should respond with the entire content that you wish to go into a dataset (no partials/paginated/javascript/etc)”
      - This URL would point to a zip file with the download contents in the form https://gateway.ireceptor.org/storage/ir_YYYY-MM-DD-TTTT_5f6cfa4d3232c.zip
  - type: this is for internal Galaxy functions, I presume the value should be “tabular”, but this might change later
      - Assuming we can send a ZIP file, pretty sure that Galaxy can handle such files.
  - name: this will be the dataset name, ideally this should be something characterizing the dataset the user has requested but it will only be used as a label in Galaxy, so the value isn’t critical at this point
      - For now, we would probably want to just use the download name for this. We can consider other options later...

@alxcost does that gel with your understanding?
@jeromejaglale any thoughts?

**Comment by alxcost** [comment]
Hi @bcorrie, @jeromejaglale, thank you for looking into this. 

Indeed! The workflow that we've determined is similar. 

Galaxy is able to read directly from ZIP archives, so we don't have to worry about extracting the files.

We didn't specify the type or the name of the dataset. But we were defaulting the data type to "tabular" on Galaxy's side anyway. I admit I'm not too familiar with the different types just yet, but I wonder if it could be beneficial to keep the type as a parameter, in case different types are considered in the future? 

Another parameter that should be POSTed to Galaxy is the `tool_id`, which seems to allow Galaxy to determine if the data was acquired from a valid Galaxy toolset. The `tool_id` should come as a URL parameter, set by Galaxy itself.

To be more clear, I'm going to share with you a tool that we prepared in the past to test this workflow. It's a "quick-and-dirty" method that seemed to work nicely. It allowed us to POST direct links to the ZIP files back to Galaxy. The workflow is documented here: https://docs.google.com/document/d/1jOWJTwjocI2qVxY_zFCyD116AgpKyVFi-nw6rmTbliI

Essentially, from Galaxy, the user is taken to this page: https://trialreceptor.inesctec.pt/galaxy-wrappers/irp-integration/?GALAXY_URL=https%3A//trialreceptor.inesctec.pt/galaxy/tool_runner&tool_id=irp-integration&sendToGalaxy=1, and here the user can paste the direct link to the ZIP file using the ireceptor format: https://gateway.ireceptor.org/storage/ir_YYYY-MM-DD-TTTT_5f6cfa4d3232c.zip. And when the user clicks the button, we are sending the data back to galaxy with a request:
```
async function postToGalaxy(url) {
    let searchParams = new URLSearchParams(window.location.search)
    let galaxyUrl = searchParams.get("GALAXY_URL");
    let toolId = searchParams.get("tool_id");

    const formData  = new FormData();
    formData.append("tool_id", toolId);
    formData.append("URL", url);

    const response = await fetch(galaxyUrl, {
        method: 'POST',
        body: formData
    });

    if (response.status == 200) {
        window.location.href = response.url.substring(0, response.url.indexOf("tool_runner"));
    }
}
```

This was a pure JavaScript approach, so everything happens on the client-side. But it should be an identical process using PHP if we want to keep things server-side.

What do you think? Let me know if you'd like me to pick this up.

**Comment by jeromejaglale** [comment]
About ``GALAXY_URL`` and ``tool_id``: are they going to always be the same?

When Galaxy sends the user to the gateway, the gateway can save ``GALAXY_URL`` and ``tool_id`` into the user's session, so anytime the user goes to the downloads page, the option to send data to galaxy is **always** there. These values would be refreshed anytime ``GALAXY_URL`` and ``tool_id`` are parameters of the downloads page URL: ``/downloads?GALAXY_URL=...&tool_id=...``

If that doesn't make sense, the downloads page can display the "Send to Galaxy" button **only** when ``GALAXY_URL`` and ``tool_id`` are parameters of the download page URL: ``/downloads?GALAXY_URL=...&tool_id=...``

**Comment by alxcost** [comment]
Hi Jerome, I relayed the question to the ImmuneML slack channel and either workflow is fine but always having the button would be more convenient.

I also did some researched that I shared in the channel, and I found an external datasource that behaves similarly when it comes to keeping Galaxy's data in session:

http://archaea.ucsc.edu/cgi-bin/hgTables
If you press "get output" it seems to simply output whatever query you've made.

But if you access the same webpage from a Galaxy instance that sets a `GALAXY_URL` like: http://archaea.ucsc.edu/cgi-bin/hgTables?GALAXY_URL=https%3A//usegalaxy.org/tool_runner&tool_id=ucsc_table_direct_archaea1&sendToGalaxy=1&hgta_compressType=none&hgta_outputType=bed,
When you press "get output", it takes you to a new page where you can customize the data that will be sent to Galaxy. And even if you close and reopen the page with no `GALAXY_URL`, it seems to persist that you've previously reached the page through a Galaxy instance. Clearing cookies/session storage restores default behavior.

From a development point of view, not having to deal with sessions would probably be faster and much easier to implement. So please also let me know your availability to make such changes. I'd be glad to help you as I'm comfortable with Laravel and Frontend development.

**Comment by bcorrie** [comment]
I believe we have this working - at least in the alpha state. I will mark this as Done after todays meeting unless anyone (@alxcost @jeromejaglale) has any objections.

**Comment by bcorrie** [comment]
Marking this as Done...
