### ISSUE TITLE
Additional translation of Cellranger AIRR TSV output for VDJServer

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/specifications#20]
Have manual scripts at the moment, need to integrate into Cellranger app.

**Comment by bcorrie** [comment]
@schristley curious as to the transformation required, we are starting to look at the cellranger v4.0 output, and it seems like it should be able to be loaded fairly directly, although just started looking at this...

**Comment by bcorrie** [comment]
Opps, clicked the wrong button 8-)

**Comment by schristley** [comment]
> @schristley curious as to the transformation required, we are starting to look at the cellranger v4.0 output, and it seems like it should be able to be loaded fairly directly, although just started looking at this...

It does appear to meet the minimal requirements, i.e. passes validation, but it's pretty minimal regarding annotations. We (VDJServer) like to provide the fuller set of annotations output by IgBlast. However, the main issue is the lack of alleles on the gene calls. I've communicated about this with Wyatt @ 10x and apparently 10x is legally prevented by IMGT from supplying alleles in the reference database they supply to customers.

**Comment by bcorrie** [comment]
Hmm, interesting... Do you know if cellranger has a mechanism to choose to use a different reference database. Presumably, I as a cellranger user, could download the IMGT reference, ask cellranger to use it, and annotate with that, which would give the alleles I presume? I can see a restriction on the reference DB that 10X provides, but is there a way to point to a local copy, which I as a researchers am allowed to download for use?

**Comment by schristley** [comment]
It's a parameter to cellranger, as 10x provides a human and mouse reference. However, you would need to provide the germline in the proper format with the necessary annotations. I'm not sure what that all entails.

**Comment by schristley** [comment]
Have integrated into cellranger app, still need to generate `Cell` objects but that will be done in #21
