### ISSUE TITLE
How do we handle productive and non-productive sequences?

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/specifications#3]
Do we need to treat them differently?

**Comment by bcorrie** [comment]
Non-productive rearrangements would conceivably be missing some of the gene calls, which we will have to handle.

Presumably, if a rearrangements has no gene call for a specific stats field (e.g. d_call) we would know this because the stats API returns a total count for each repertoire. So number of rearrangements with no d_calls would be total - sum(d_call counts). The consumer of the data could choose to show that value in a "None" category or just show the d_calls with values. So far so good - we can handle missing gene calls if they are missing due to not being productive.

How important is it that we can do stats on just productive rearrangements in a specific repertoire? 

I don't think we want to always do just use productive rearrangements, as there is potential value in the unproductive rearrangements. So I think two questions:

1. Does it make sense to JUST do stats on non-productive rearrangements?
2. Do we want to make it possible to quickly do stats on JUST productive rearrangements?

Right now the spec has no mechanism to do this, and because it is at the per repertoire level no "filters" on rearrangement filters are currently supported. Do we want to change that?

**Comment by bussec** [comment]
IMO it would make sense to allow comparisons between productive and non-productive, as the latter one should not show a selection bias (as they are not expressed). This could apply to parameters like V segment usage or various SHM counts.

**Comment by bcorrie** [comment]
So do we add this to the query:

```
  "auth_token": "string",
  "repertoires": [
    {
      "repertoire_id": "REPID_4598",
      "sample_processing_id": "SPID_1",
      "data_processing_id": "DPID_1"
      "productive": true
    }
  ]
}
```
Where if `productive` is missing you get everything for that Repertoire. This means it is `required:false` and `nullable:false`

Personally, I think this is getting messy, as this is going down the filtering data path (so it is leaning towards analysis), but I can see how it is very useful AND I can see how we could easily cache it per repertoire on the repository side.

**Comment by bcorrie** [comment]
Hmm, I think if we do this, we should do it this way:

```
{
  "auth_token": "string",
  "repertoires": [
    {
      "repertoire_id": "REPID_4598",
      "sample_processing_id": "SPID_1",
      "data_processing_id": "DPID_1"
    }
  ],
  "productive":true
}
```
We don't want to have productive part of the repertoire description, it should be a separate parameter.

In this case as above, if `productive` is missing you get everything for that Repertoire. This means it is `required:false` and `nullable:false`

**Comment by bcorrie** [comment]
Hmm, the above doesn't work either 8-) How about:
```
{
  "auth_token": "string",
  "repertoires": [
    "repertoire":{
      "repertoire_id": "REPID_4598",
      "sample_processing_id": "SPID_1",
      "data_processing_id": "DPID_1"
    },
    "productive":true
  ]
}
```

**Comment by schristley** [comment]
You want the `productive` flag to be set for each individual repertoire versus for the whole API request? I guess I'm okay either way but it seems simpler to just have a single parameter for the whole request, but it's certainly more flexible if it's a per repertoire flag.

**Comment by bcorrie** [comment]
Yes, I thought about that as well... Not tied to either approach particularly, seemed more flexible per repertoire though as you say.

**Comment by bzimonja** [comment]
Yeah, I think it's  easier doing it for the whole request, because otherwise, you need to keep track of which repertoires you asked 'productive' for yourself, since right now response will just give you "key" and "count" and won't indicate whether count is productive or not.

Alternatively, we could instead of "key","count" have "key", "count" , "count_productive" in response, either always or when you specify the "productive" flag.

**Comment by schristley** [comment]
> Yeah, I think it's easier doing it for the whole request, because otherwise, you need to keep track of which repertoires you asked 'productive' for yourself, since right now response will just give you "key" and "count" and won't indicate whether count is productive or not.

That's a good point. I can see myself requesting both (productive/non-productive) at the same time, so there should be something in the output to let me know which is which

```
{
  "auth_token": "string",
  "repertoires": [
    {
      {
        "repertoire_id": "REPID_4598",
        "sample_processing_id": "SPID_1",
        "data_processing_id": "DPID_1"
      },
      "productive":true
    },
    {
      {
        "repertoire_id": "REPID_4598",
        "sample_processing_id": "SPID_1",
        "data_processing_id": "DPID_1"
      },
      "productive":false
    }
  ]
}
```

**Comment by bcorrie** [comment]
So rather than having to ask for one or the other, do we give both a total and a productive count in every response (given that unproductive = total - productive) as @bzimonja suggests?

This is making the Stats API treat `productive` as special, but we are doing that anyway in allowing it as a "filter" to the query. I kind of like this, as you just ask for the repertoires of interest, and you get back the stats. You get back a count for the total and a count for the productive rearrangements at the same time. The consumer of the data deals with which of the stats they want...

**Comment by schristley** [comment]
Note that the productive/non-productive applies to /rearrangement but not to /clones, as presumably all clones have to be productive. So we might want to design so that we can keep commonality between the two end points. Maybe the incoming request has different parameters (as it has to because different ids) while the responses are common?

**Comment by bzimonja** [comment]
Hmmm...I was going to say, if response is the same, you can't tell whether it's productive or not but, then I realized, that's generally true of ADC API and filters.

It is equivalent to sending /rearrangement request with productive:true and facets:repertoire_id. You can see from response the repertoire_id and count, but you have to know the request to interpret the response correctly. So maybe we can treat 'productive' as a filter on stats for rearrangements, and ignore for clones.

It would probably be easier in that case to make 'productive' apply to the entire request, rather than ask some repertoires for productive count and others for all.

**Comment by yyweiss** [comment]
Wouldn't it be more simple on the level of API description to allow general queries to describe the  "repertoires" array, and let the backend decide if it supports such a filter?

You can then decide that a provider following the stats API version x must allow queries on specific fields. It can also be recommended to allow queries on other fields. This way, a provider can decide how many resources to allocate to caching or computation.

An appropriate error response can be returned if an unsupported  query is submitted.

**Comment by bcorrie** [comment]
> Wouldn't it be more simple on the level of API description to allow general queries to describe the "repertoires" array, and let the backend decide if it supports such a filter?

Not sure I follow, can you elaborate? What kind of general queries are you talking about?

**Comment by yyweiss** [comment]
`  "repertoires": [
{
  "filters":{
    "op":"and",
    "content": [
      {"op":"=","content": {"field":"repertoire_id","value":"REPID_4598"}},
      {"op":"=","content": {"field":"sample_processing_id","value":"SPID_1"}},
      {"op":"=","content": {"field":"data_processing_id","value":"DPID_1"}},
      {"op":"=","content": {"field":"productive","value":"true"}}
    ]
  }
},
{
  "filters":{
    "op":"and",
    "content": [
      {"op":"=","content": {"field":"repertoire_id","value":"REPID_4598"}},
      {"op":"=","content": {"field":"sample_processing_id","value":"SPID_1"}},
      {"op":"=","content": {"field":"data_processing_id","value":"DPID_1"}},
      {"op":"=","content": {"field":"productive","value":"false"}}
    ]
  }
}
]`

The idea is to allow something like this. It reuses the query language, so you don't have to define a new API. It is more simple (even though the requests are a little longer) because you don't have to debate (at the API level)  if to support requests on special fields such as "productive". Even if a decision is made not to require support for such queries, the more general language allows a provider to support such extensions without having to worry about a conflict with a future API.

**Comment by bcorrie** [comment]
In doing the above, you have to implement the full set if queries on the Stats API, so you are duplicating the query functionality on both APIs. In addition, the Stats API is intended as a simple API to perform quick stats on full repertoires, so we explicitly have defined it such that the Stats API works on full Repertoires (or at least a combo of repertoire_id, data_processing_id, and sample_processing_id). We are kind of breaking that rule with our productive feature, but the intent isn't to provide a general rearrangement level query/filter capability for the Stats API.

I think the type of query that you are suggesting is probably more appropriate for the Analysis API where you are able to perform an analysis (e.g. gene usage) on an arbitrary query against the /rearrangement API.

**Comment by yyweiss** [comment]
My goal for these queries is not that it be **required** to implement the full set of queries, but that it be **possible** to implement more queries than required by the API. Once you break the rule once for productive sequences, it wouldn't be surprising if it was broken for another feature too.

If you don't want to view these as (potentially general) queries of rearrangements, I would view them as features or variants of statistics, and every statistic could have its own set of variants which it supports.

Such a structure could also solve the problem of how to count multiple V/D/J calls #2 .

**Comment by bcorrie** [comment]
If I understand what you are saying correctly, that is the approach we are taking. We don't want to support general queries on rearrangements, as that is too computationally expensive for an interactive API (which is what the Stats API is supposed to be). That is what the Analysis API is for. We are considering more than just the basic stats as "features" in a way. That is if we think a specific variant of a specific Stat is valuable to the community, we add it to the spec explicitly. We handle that by extending the controlled vocabulary of the set of Stats that you can ask for for that entry point. This is what we are currently planning for productive as well as handling special cases for gene usage with ambiguous gene calls.

So what we have is a mechanism for a controlled extension of the Stats spec through controlled vocabulary, not through general queries. For example, the plan is to have a `v_call_productive` statistic in addition to the normal `v_call`. Similarly, if we wanted to define a V allele stat that counted multiple v_calls in a specific way that is different that the basic `v_call` we would define a different stat for that (e.g. `v_call_count_all`).

So it is easy to extend the API to include new Stats but it is done in a controlled and well defined way.

**Comment by schristley** [comment]
> So it is easy to extend the API to include new Stats but it is done in a controlled and well defined way.

I agree this is a good plan for an initial API. It keeps the implementation constrained. As we fill out more statistics, we can gauge whether the design is sufficient or not.
