### ISSUE TITLE
Draft of AIRR Clone API

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/specifications#31]

**Comment by bcorrie** [comment]
I had created this branch a week or two ago: https://github.com/airr-community/airr-standards/tree/cell_api

**Comment by bcorrie** [comment]
And a pull request to merge. The iReceptor Turnkey is now able to load MiXCR clone data into a repository and we are working on implementing this draft API. 

https://github.com/airr-community/airr-standards/pull/474

**Comment by bcorrie** [comment]
Closing this issue - AIRR Clone API merged into master.
