### ISSUE TITLE
Definition of count_object for stats API

### ISSUE THREAD

**Issue by bzimonja** [ireceptor-plus/specifications#4]
Stats for /rearrangement/count are supposed to return count_object_response (unless there's an error).

The response has an info_object and count_object. Count object seems a bit odd though

count_object:
      type: object
      description: Key-value pair count representation with total count
      properties:
        total_count:
          type: integer
        counts:
          type: object
          additionalProperties:
            type: integer

total_count would be all the rearrangements for specified repertoires filter. I'm unsure what 'counts' would have. I think it should have the repertoire_id (and maybe sample_processing_id and/or data_processing_id as asked for) and count instead. Something like:

`"counts": [
            {
                "repertoire_id": 4,
                "sample_processing_id": 425,
                "count": 1316424
            },
            {
                "repertoire_id": 12,
                "sample_processing_id": 245,
                "data_processing_id": 245,
                "count": 4381
            }
        ]
`
    
Is that more in line with what we want?

**Comment by schristley** [comment]
My initial thought for count_object was to be used where a `key` was needed for the response. For example, with gene segment usage, the keys would be the gene names like this:

```
counts: { "IGHV1-1*1": 100, "IGHV2-1*1" :150 }
```

I was trying to have `count_array` and `count_object` be generic structures for holding statistics data. That would allow client code to only handle two data structures versus a custom data structure for each end point.

I'm not sure what the current design is though as @bcorrie has changed the parameters and responses for the end points, so maybe he's not using count_object anymore.

**Comment by bcorrie** [comment]
I think this is fixed... There are count arrays as you have them above @schristley with the /count entry point just returning a single count integer per repertoire_id, sample_processing_id, data_processing_id triple.

https://github.com/ireceptor-plus/specifications/commit/d07e31642f5de666b40ce6946597bc067c4e0bc4

There are still a couple of definitions that we can get rid of but wanted to keep them in case we revert... Have a look and comment...

Response looks like this:

```
[
    {
      "repertoire": { "repertoire_id": "REPID_4598", "sample_processing_id": "SPID_1", "data_processing_id": "DPID_1" },
      "count": 42
    }
    {
      "repertoire": { "repertoire_id": "REPID_4599", "sample_processing_id": "SPID_1", "data_processing_id": "DPID_1" },
      "count": 98
    }
  ]
```

**Comment by bcorrie** [comment]
For gene counts it looks like what @schristley suggested:

```
[
          "field": "v_gene", "data": [ { "key": "IGHV1-1", "count": 42 }, { "key": "IGHV1-2", "count": 60 } ],
          "field": "d_gene", "data": [ { "key": "IGHD1-1", "count": 43 }, { "key": "IGHD1-2", "count": 70 } ]
]
```
We can (should) probably change this so it is:
```
[
          "field": "v_gene", "data": [ "IGHV1-1": 42, "IGHV1-2": 60 ],
          "field": "d_gene", "data": ["IGHD1-1": 43, "IGHD1-2": 70 ]
]
```

**Comment by bcorrie** [comment]
Made the key value change above - @schristley is there any way to provide an example with "AdditionalProperties" in OpenAPI 3.0?

**Comment by schristley** [comment]
> Made the key value change above - @schristley is there any way to provide an example with "AdditionalProperties" in OpenAPI 3.0?
> 
> [81669d6](https://github.com/ireceptor-plus/specifications/commit/81669d60af0c6c199348beed21286ed16ff70f4f)

Probably put them at the `schema` level where you put `example` for the entire schema object.

**Comment by schristley** [comment]
> I think this is fixed... There are count arrays as you have them above

@bcorrie `count_array` now looks the same as `count_object`. The reason I had `count_array` defined [this way](https://github.com/ireceptor-plus/specifications/blob/d66619e3cdf29fbb3026ba9519353608d95af8ea/stats-api.yaml#L75) is because a `key` in a JSON dictionary cannot be an integer, they are required to be strings. So when providing a junction length distribution, it could be returned this way:

```
[ { key: 5, count: 100 }, { key: 6, count: 25 }, { key: 10, count: 30} ]
```

which also allows for flexibility in ranges and binning.

**Comment by bcorrie** [comment]
@schristley I have reverted the change so we have key and count for each statistic entry again. Look OK?

https://github.com/ireceptor-plus/specifications/commit/90398d76ecff47e9cd4f24d9470e1f0b902ca16b

Note that currently the `count_object` schema is not used as the /count entry point needs more than just a key when returning a stat for a repertoire.

**Comment by schristley** [comment]
> @schristley I have reverted the change so we have key and count for each statistic entry again. Look OK?

yes.

> Note that currently the `count_object` schema is not used as the /count entry point needs more than just a key when returning a stat for a repertoire.

You could use `count_object` for the gene usage end point. I think I originally had it that way. There, we can probably assume that all gene names are strings, and a dictionary object might be a more efficient data structure for lookup versus an array. Unclear though, may depend upon how the client wants to manipulate the data, or if we want the API to return the data in a specific ordering, which the array allows.

**Comment by bcorrie** [comment]
> You could use `count_object` for the gene usage end point. I think I originally had it that way. There, we can probably assume that all gene names are strings, and a dictionary object might be a more efficient data structure for lookup versus an array. Unclear though, may depend upon how the client wants to manipulate the data, or if we want the API to return the data in a specific ordering, which the array allows.

I kind of like having the responses consistent between the entry points, as I can see adding more entry points and it would be a pain to have clients have to handle different count structures for different query entry points.

My initial thought is that we don't want to enforce the API response to have any ordering (e.g. thou shalt sort key before returning), as I think that would be messy. The client that consumes the [{"key":"IGHV1", "count":42}, ...] can sort the keys or the counts, depending on what they want to do with the data.

**Comment by schristley** [comment]
> I kind of like having the responses consistent between the entry points, as I can see adding more entry points and it would be a pain to have clients have to handle different count structures for different query entry points.

I see your point. I almost wish it could be complete though, that is the response schemas are identical for all end points. The responses for junction length and gene usage are structured different anyways, so the client is going have to interpret them differently regardless. You could make them the same but it requires giving up the complex array-of-arrays for gene usage.

**Comment by bcorrie** [comment]
Is it crazy to have /rearrangement/stats 

and then tell it as an array of parameters which stats you want:

```
{
  "auth_token": "string",
  "repertoires": [
    {
      "repertoire_id": "REPID_4598",
      "sample_processing_id": "SPID_1",
      "data_processing_id": "DPID_1"
    }
  ],
  "fields": [
    "count",
    "junction_aa_length",
    "v_subgroup",
    "v_gene",
    "d_call",
    "c_call"
  ]
}
```
One call gets them all, one call to bind them 8-)

Alternatively you could make the above six different entry point calls...

**Comment by bcorrie** [comment]
Or when you look at it, we could go the other way, and add the array to all fields, assuming there are multiple fields for each entry point that might be of interest. For example for junction_length we could have:
```
{
  "auth_token": "string",
  "repertoires": [
    {
      "repertoire_id": "REPID_4598",
      "sample_processing_id": "SPID_1",
      "data_processing_id": "DPID_1"
    }
  ],
  "fields": [
    "junction_aa_length",
    "junction_length"
  ]
}
```

**Comment by bzimonja** [comment]
I like the second one. If parameters are optional, then something like junction_length or rearrangement_count won't need fields, but can accept it with a single value currently available ("junction_aa_length" and "rearrangements" or something similar). 

Would it make sense to standardize the rearrangement/count response to something like:

      "repertoire": { "repertoire_id": "REPID_4598",  "sample_processing_id": "SPID_1", "data_processing_id": "DPID_1" },
      "fields": 
        [
          "field": "rearrangement_count", "total": 102, "data": [ { "key": "rearrangements", "count": 102 } ]
        ]

Or would this be incorrect, due to rearrangement_count not being an AIRR field (yet?) ?

**Comment by schristley** [comment]
> Or when you look at it, we could go the other way, and add the array to all entry points, assuming there are multiple fields for each entry point that might be of interest.

That could work. I'm okay with an end point having a controlled vocabulary of only one field.

**Comment by bcorrie** [comment]
@schristley @bzimonja I have made it such that the response is now consistent across all API entry points. 

/junction_length can take on the junction_aa_length and junction_length fields

/gene_usage can take all of VDJC call/gene/subgroup combinations

/count currently takes on the field "repertoire_id". For consistency, I wanted to use a field_name that we were essentially faceting on, so this seemed to make sense??? Not 100% sure about that though, but it felt like a field name should be provided.

Do you want to review? 

We need to still resolve the correct behaviour when a sample_processing_id isn't provide as input as per #5

**Comment by bzimonja** [comment]
I was implementing the more complicated, gene usage-like response for the junction_length and I think it works. It would be tempting to implement a single entry point, but I think this is clearer. Potentially, we could replace /junction_length with /junction if we wanted fields "junction", "junction_aa", "junction_length", "junction_aa_length" but I'd be worried about the size of the response.

For /count, the best I can think of is to have "key":"rearrangement_count" or something similar. It's not an AIRR term but that's what we are really faceting on.

**Comment by schristley** [comment]
Looks good, you can collapse count_response, junction_length_response and gene_usage_response if you want as they are identical.

**Comment by bzimonja** [comment]
Hmm...related to the 'productive' discussion, if we are going to collapse on a single response, I'd say "rearrangement_count" should go in the "field" and "key" would be just "count". That way, if we want to, we can add "count_productive" or even "duplicate_count_total" to the response as keys, if we wanted to...

**Comment by bcorrie** [comment]
I think I like that... "rearrangement_count", "duplicate_count" would be possible as operations that are "summing" an internal count field, with rearrangement_count being special as it is summing everything with an implicit internal count field of 1. This is suggesting that we are generalizing the /count API a bit to actually be a sum operation on a given rearrangement count field...
