### ISSUE TITLE
Determine Gateway -> Stats interface

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/specifications#42]
<script>
	var statsHTMLBlock = "draw_stats_here";
        /* stats_json Provided by the Gateway based on Stats queries */
        var statsJSONData = {!! $stats_json !!};
</script>
This would result in some graphs of the data in stats_json being drawn in the DIV block with the label "draw_stats_here"

What else is required???

**Comment by bcorrie** [comment]
Copied from https://github.com/ireceptor-plus/WP1/issues/9

**Comment by bcorrie** [comment]
@marcoamarooliveira I think we are done with defining this, as per the interface you are implementing now. Do you have a github link to a repository for this code? If so, we can link to that and close this issue...

**Comment by marcoamarooliveira** [comment]
GitHub link for the Visualization Library: https://github.com/ireceptorplus-inesctec/airrvisualizationlibrary

**Comment by bcorrie** [comment]
Closing this issue...
