### ISSUE TITLE
Provide javascript code for visualization

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/specifications#43]

**Comment by bcorrie** [comment]
@marcoamarooliveira @jeromejaglale we can use this issue to track coordination around the javascript code...

**Comment by marcoamarooliveira** [comment]
Javascript GitHub repository: https://github.com/ireceptorplus-inesctec/airrvisualizationlibrary

**Comment by jeromejaglale** [comment]
@marcoamarooliveira could you add a quick howto about how to generate the ``lib`` and ``dist`` folders required by iRplusVis_APP.html and ImmuneDb_APP.html?

**Comment by marcoamarooliveira** [comment]
Was updating it.
Just run :
`npm install`
followed by :
`npm run build`

If you need access to sources, instead of `build `use `build:dev` .

**Comment by jeromejaglale** [comment]
With `npm install`, I get:
```
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/vagrant/ireceptor_gateway/public/airrvisualizationlibrary/node_modules/aggregate-error/node_modules/indent-string/package.json.157217220
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/vagrant/ireceptor_gateway/public/airrvisualizationlibrary/node_modules/aggregate-error/node_modules/indent-string/package.json.157217220'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-11-09T22_31_46_938Z-debug.log
```

And then with `npm run build`:
```
> airrvisualizationlibrary@0.2.0 build /home/vagrant/ireceptor_gateway/public/airrvisualizationlibrary
> run-s clean:dist setup:dist & browserify    -u highcharts -u highcharts/highcharts-3d -u highcharts/modules/exporting -u highcharts/modules/data -u highcharts/modules/drilldown -t [browserify-versionify] -t [ babelify ] -t [uglifyify] -p [ @jsdevtools/browserify-banner --file src/banner.txt ] ./src/index.js                                           -o ./dist/airrvisualization.js

sh: 1: run-s: not found
sh: 1: browserify: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! airrvisualizationlibrary@0.2.0 build: `run-s clean:dist setup:dist & browserify    -u highcharts -u highcharts/highcharts-3d -u highcharts/modules/exporting -u highcharts/modules/data -u highcharts/modules/drilldown -t [browserify-versionify] -t [ babelify ] -t [uglifyify] -p [ @jsdevtools/browserify-banner --file src/banner.txt ] ./src/index.js                                           -o ./dist/airrvisualization.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the airrvisualizationlibrary@0.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2020-11-09T22_32_35_028Z-debug.log
```

Did I forget to do something? Sorry, I'm not familiar with npm.

**Comment by marcoamarooliveira** [comment]
That error in the `install` process is strange. I really tried to get the error but was not able to do it. Instead I did found out that I had an error during the build process in Linux environments. SOLVED: I already updated the script in package.json. 

How I tested the build in Linux (using a windows 10 OS):
- Install [Multipass](https://multipass.run/) (v.1.5.0+win) on windows machine to have a clean Ubuntu Linux 20.04.1 LTS (Focal Fossa);
- Open a Shell prompt within the Ubuntu machine;
- Update ubuntu packages using `sudo apt update`, `sudo apt-get update` and `sudo apt-get upgrade`;
- Install npm using `sudo apt-get install npm` (not installed by default) - Version installed: '6.14.4';
- Create and move into a directory to clone the [AirrVisualization GitHub project](https://github.com/ireceptorplus-inesctec/airrvisualizationlibrary) using `sudo mkdir /opt/dev` and `cd /opt/dev`;
- Clone the repository using `sudo git clone https://github.com/ireceptorplus-inesctec/airrvisualizationlibrary.git` (git is installed by default on Ubuntu);
- Use npm to install (dev-)dependencies using `npm install`;   

    It will probably throw errors due to write permissions:
> npm WARN checkPermissions Missing write access to /opt/dev/airrvisualizationlibrary  
> npm ERR! code EACCES  
> npm ERR! syscall access  
> npm ERR! path /opt/dev/airrvisualizationlibrary  
> npm ERR! errno -13  
> npm ERR! Error: EACCES: permission denied, access '/opt/dev/airrvisualizationlibrary'  
> npm ERR!  { [Error: EACCES: permission denied, access '/opt/dev/airrvisualizationlibrary']  
> npm ERR!   stack:  
> npm ERR!    'Error: EACCES: permission denied, access \'/opt/dev/airrvisualizationlibrary\'',  
> npm ERR!   errno: -13,  
> npm ERR!   code: 'EACCES',  
> npm ERR!   syscall: 'access',    
> npm ERR!   path: '/opt/dev/airrvisualizationlibrary' }  
> npm ERR!  
> npm ERR! The operation was rejected by your operating system.  
> npm ERR! It is likely you do not have the permissions to access this file as the current user  
> npm ERR!  
> npm ERR! If you believe this might be a permissions issue, please double-check the  
> npm ERR! permissions of the file and its containing directories, or try running  
> npm ERR! the command again as root/Administrator.  
>
> npm ERR! A complete log of this run can be found in:  
> npm ERR!     /home/ubuntu/.npm/_logs/2020-11-10T11_22_24_560Z-debug.log  

  - If the above errors occur, change the folder owner to your user `sudo chown -R <user>:<user> ./` or give permission to all users `sudo chmod -R 777 ./`. You could also use `sudo` but I don't recommend. And try the install command again - either way user will have write permissions and the install will (at least should)  run smoothly.
  
- use npm to build the library using `npm run build` or `npm run build:dev`  

I got the `airrvisualization.js` file within `dist` folder.

Please check npm version (?), write permissions(?), update the repository and try again.

**Comment by jeromejaglale** [comment]
It was the Vagrant path length problem you mentioned: https://docs.npmjs.com/common-errors#running-a-vagrant-box-on-windows-fails-due-to-path-length-issues. When I tried in a directory with a shorter path it worked.. And I just had to do:
```
git clone https://github.com/ireceptorplus-inesctec/airrvisualizationlibrary.git
cd airrvisualizationlibrary/
npm install
npm run build
```

But I got a warning with `npm install`:
```
> airrvisualizationlibrary@0.2.0 setup:lib:highcharts /home/ubuntu/airrvisualizationlibrary
> copyfiles -u 1  node_modules/highcharts/** ./lib 

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 769 packages from 348 contributors and audited 771 packages in 18.405s
```
And when running the HTML files, in the browser console, it says that the `Highcharts Drilldown` module is missing?

```
Array(5) [ "influenza", "ms", "ppg_shlomchik2", "sykesAnchoring2020", "lp15" ]
airrvisualization.js:233:3311
Read 5 studies, in a total of 280 statistic values. airrvisualization.js:233:4137
{} airrvisualization.js:245:5056
properties is instance of Properties airrvisualization.js:245:10211
201110T155523 HichartsChart ERROR: 

Highcharts Drilldown module not available airrvisualization.js:224:1721
Uncaught Required Highcharts Drilldown module not available
```

Is `package.json` missing something?

**Comment by marcoamarooliveira** [comment]
@jeromejaglale,
The Warning about `fsevents` is just that a warning and `fsevents` is not required. **Not an issue.**

Now for the 
```
ERROR: 

Highcharts Drilldown module not available airrvisualization.js:224:1721
```
It means that the **Highchart's Drilldown module is not loaded**.

By removing Highcharts library from the `airrvisualization `library bundle (as was requested), I depend on external loading of Highcharts modules. You can see an example in *_APP.html documents on the repository.

At the moment I'm checking the existence of `highcharts` library and 4 of its modules: `highcharts-3d`; `data`; `exporting `and `drilldown`.

So you need to ensure that those modules are loaded before using `airrvisualization` objects. If needed, after `npm install` you can find `highcharts` inside `lib/` folder of the project.

```
        <script src="lib/highcharts/highcharts.js"></script> 
        <script src="lib/highcharts/highcharts-3d.js"></script> 
        <script src="lib/highcharts/modules/data.js"></script> 
        <script src="lib/highcharts/modules/exporting.js"></script> 
        <script src="lib/highcharts/modules/drilldown.js"></script> 
        <script  src="dist/airrvisualization.js"></script>  
```

**Comment by jeromejaglale** [comment]
The HTML files do link to highcharts in the `lib/` folder. But the highcharts `modules/` folder is missing:
```
Loading failed for the <script> with source “http://.../airrvisualizationlibrary/lib/highcharts/modules/exporting.js”.
Loading failed for the <script> with source “http://.../airrvisualizationlibrary/lib/highcharts/modules/drilldown.js”.
```

It looks like this line in `package.json` did not copy the `modules` folder?
`    "setup:lib:highcharts": "copyfiles -u 1  node_modules/highcharts/** ./lib ",`

**Comment by marcoamarooliveira** [comment]
Can you share the vagrantfile (or any specs of your dev system) so I can test in a similar system? 

An immediate work around is to download a zip file with highcharts and all its modules from https://www.highcharts.com/blog/download/ or use the direct link to Highcharts CDN at https://code.highcharts.com/.

Nevertheless, as per the documentation in https://www.npmjs.com/package/copyfiles:

> if your terminal doesn't support globstars then you can quote them
> `copyfiles -f ./foo/**/*.txt out`
> does not work by default on a mac
> but
> `copyfiles -f "./foo/**/*.txt" out`
> does.

So, I updated the scripts to have the globstars quoted. Works for me.

**Comment by jeromejaglale** [comment]
Yes, the `modules` folder is copied now. Thanks you!

**Comment by bcorrie** [comment]
@marcoamarooliveira @jeromejaglale I think we can consider this done, going to close unless anyone objects.

**Comment by bcorrie** [comment]
Closing...
