### ISSUE TITLE
What does `token` do?

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/specifications#6]
In the current spec, there is a `token` field in the Stats requests, and it is unclear to me where this came from??? @schristley any thoughts, did you add this and if so what is it doing? 8-)

For example:

https://github.com/ireceptor-plus/specifications/blob/a11c05c259962d42c60b5b8b8441ff3a7d52bc24/stats-api.yaml#L298

**Comment by schristley** [comment]
It's a placeholder for a security user authorization token.

**Comment by bcorrie** [comment]
Changed the name to auth_token to be a bit more clear as to the intent.
