### ISSUE TITLE
Write report for D7.2

### ISSUE THREAD

**Issue by bcorrie** [ireceptor-plus/specifications#71]
@bussec this Milestone (https://github.com/ireceptor-plus/specifications/milestone/12) was created but had no issues. For completeness I created a write report issue - which I believe we are done with... If you agree can you close this issue, and then the Milestone will be 100% completed... 8-)

Sorry to make work, but trying to clean up the Milestones/Issues...

**Comment by bussec** [comment]
No problem, thanks for the reminder.
