### ISSUE TITLE
/ and /info end points for stats and analysis APIs

### ISSUE THREAD

**Issue by schristley** [ireceptor-plus/specifications#9]
The ADC API has a / end point which provides a simple service heartbeat, and an /info end point which provides info about the service. Do we want to keep them separate for the stats and analysis APIs, or combine them?

The idea for separate end points is that they could perform different functions, the / end point might check database connectivity and etc. to verify the service is operational, while the /info end point might return static information.

**Comment by bcorrie** [comment]
I think having a unique endpoint for the Stats API makes sense. We are talking /irplus/v1/stats and /irplus/v1/stats/info correct?

**Comment by bcorrie** [comment]
I will add it, I am going to do some work on it later today based on our Vis discussion today.

**Comment by schristley** [comment]
Sounds good, it's in the analysis API now so feel free to copy/paste the schema and paths

**Comment by bcorrie** [comment]
Done, see https://github.com/ireceptor-plus/specifications/commit/dd47fe91b11837fc7d10cd42815f6cf3f54bed51
